apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "serviceAccountName" . }}
  namespace: {{.Values.namespace}}
automountServiceAccountToken: {{ .Values.serviceAccount.automountServiceAccountToken }}